import type { Metadata } from "next";
import "./globals.css";
import '@stream-io/video-react-sdk/dist/css/styles.css'; 
import { Providers } from "./providers";


export const metadata: Metadata = {
  title: "Meet AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
          <Providers>{children}</Providers>
      </body>
    </html>
  );
}
